services:
  nodejs:
    image: node:14
    container_name: nodejs-app
    volumes:
      - ./:/usr/src/app  # Mount your src folder where app.js is located
    working_dir: /usr/src/app
    command: ["node", "app.js"]  # Ensure the Node.js app starts from app.js in src
    expose:
      - "3000"
    networks:
      - backend
  
  crs-nginx:
    container_name: modsec2-nginx
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    depends_on:
      - nodejs
    networks:
      - backend

  # nginx:
  #   build:
  #     context: ./nginx  # Docker build context for Nginx with ModSecurity
  #     dockerfile: Dockerfile  # Dockerfile for building Nginx with ModSecurity
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config
  #   depends_on:
  #     - nodejs
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge