services:
  nodejs:
    image: node:14
    container_name: nodejs-app
    volumes:
      - ./:/usr/src/app  # Mount your src folder where app.js is located
    working_dir: /usr/src/app
    command: ["node", "app.js"]  # Ensure the Node.js app starts from app.js in src
    expose:
      - "3000"
    networks:
      - backend
  
  crs-nginx:
    container_name: modsec2-nginx
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    depends_on:
      - nodejs
    networks:
      - backend
  
  mysql: 
    image: mysql:9.2.0
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATBASE: users
    ports: 
      - '3600:3600'
    volumes: 
      - db_data:/var/lib/mysql
      - ./database/initdb/user.init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

networks:
  backend:
    driver: bridge